### ISSUE TITLE
No recipe to resolve 'proxyMiddleware'

### ISSUE THREAD

**Issue by larsfroelich** [virtkick/http-master#128]
I'm getting the following error (repeatedly) when trying to launch the proxy:

> Worker 305 failed with code 1/null ... starting replacement
> ^CUnexpected token {
> [306] [Uncaught exception] Error: No recipe to resolve 'proxyMiddleware'
>     at DI.resolve (/usr/local/lib/node_modules/http-master/src/di.js:150:11)
>     at DI.resolve (/usr/local/lib/node_modules/http-master/src/di.js:146:28)
>     at passEntryToModule (/usr/local/lib/node_modules/http-master/modules/middleware/router.js:49:23)
>     at parseSingleEntry (/usr/local/lib/node_modules/http-master/modules/middleware/router.js:63:12)
>     at parseEntry (/usr/local/lib/node_modules/http-master/modules/middleware/router.js:78:12)
>     at /usr/local/lib/node_modules/http-master/src/DispatchTable.js:92:25
>     at Array.forEach (native)
>     at new DispatchTable (/usr/local/lib/node_modules/http-master/src/DispatchTable.js:78:29)
>     at /usr/local/lib/node_modules/http-master/modules/middleware/router.js:90:29
>     at Array.map (native)
>     at Object.RouterMiddleware.entryParser (/usr/local/lib/node_modules/http-master/modules/middleware/router.js:86:42)
>     at EventEmitter.createHandlers (/usr/local/lib/node_modules/http-master/src/HttpMasterWorker.js:199:23)
>     at EventEmitter.handleConfigEntryAfterLoadingKeys (/usr/local/lib/node_modules/http-master/src/HttpMasterWorker.js:297:33)
>     at /usr/local/lib/node_modules/http-master/src/HttpMasterWorker.js:130:39
>     at EventEmitter.loadKeysforConfigEntry (/usr/local/lib/node_modules/http-master/src/HttpMasterWorker.js:121:5)
>     at EventEmitter.handlePortEntryConfig (/usr/local/lib/node_modules/http-master/src/HttpMasterWorker.js:126:26)

**Comment by jaredrada** [comment]
+1 same issue here
