### ISSUE TITLE
TypeError: Cannot call method 'loadSession' of null

### ISSUE THREAD

**Issue by Nowaker** [virtkick/http-master#90]
Number of exceptions: ~10
Seen on: 0.7.14

```
[2014-11-08T22:17:15.504Z] [14] [Uncaught exception] TypeError: Cannot call method 'loadSession' of null
    at callback (tls.js:836:14)
    at process.<anonymous> (/usr/lib/node_modules/http-master/worker.js:48:9)
    at process.g (events.js:180:16)
    at process.emit (events.js:95:17)
    at process.on.config (/usr/lib/node_modules/http-master/worker.js:77:11)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
[2014-11-08T22:17:15.507Z] Worker 14 failed with code 1/null ... starting replacement
```

**Comment by Nowaker** [comment]
Frequency: ~3/day
